version: '3.8'

services:
  bot:
    build: .
    container_name: training-bot
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telegram_bot
      MYSQL_USER: bot_user
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
